services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=telemedicina
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123          # <- adiciona a senha do usuário
      - MYSQL_ROOT_PASSWORD=123
